name: 'Cherry-picker on comment'
description: 'Cherry-picks the commit when the issue is created after the bazel-io X.Y.Z comment'
inputs:
  token:
    description: 'The GitHub token'
    required: false
    default: ${{ github.token }}
  triggered-on:
    required: true
    default: ${{ github.triggered-on }}
  pr-number:
    required: true
    default: ${{ github.pr-number }}
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  
    # - name: Install Dependencies
    #   run: pip install -r requirements.txt
    #   shell: bash
    - name: Pass Inputs to Shell
      run: |
              echo "INPUT_TRIGGERED_ON=${{ inputs.triggered-on }}" >> $GITHUB_ENV
              echo "INPUT_TOKEN=${{ inputs.token }}" >> $GITHUB_ENV
              echo "INPUT_PR_NUMBER=${{ inputs.pr-number }}" >> $GITHUB_ENV
      shell: bash
    - name: Run python index.py
      run: |
              chmod +x ${{ github.action_path }}/index.py
              python ${{ github.action_path }}/index.py
      shell: bash
    # - name: Run python index.py
    #   run: python continuous-integration/actions/cherry-picker/on-comment/index.py
    #   shell: bash
    # using: 'node16'
    # main: 'index.js'